name: My first workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: source HikariCP.sh &>/dev/null
